# Generated by Django 6.0.5 on 2026-06-04 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('INBOUND', 'Receiving New Stock'), ('OUTBOUND', 'Shipping to Customer'), ('TRANSFER', 'Moving between Warehouses')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Not Started'), ('IN_PROGRESS', 'Worker is doing it'), ('COMPLETED', 'Finished')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_tasks', to='inventory.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_tasks', to='inventory.warehouse')),
            ],
        ),
    ]
