# Generated by Django 6.0.5 on 2026-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_purchase_purchaseitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
